import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, user-scalable=yes" />
        <title>Хакасия</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <header id="header" className="header">
          <div className="container">
            <div className="header__body">
              <a className="header__logo" href="#welcome"></a>
              <div className="header__burger">
                <span> </span>
              </div>
              <nav className="header__menu">
                <ul className="header__list">
                  <li><a href="#welcome" className="header__link">Главная</a></li>
                  <li><a href="#attractions" className="header__link">Достопримечательности</a></li>
                  <li><a href="#tours" className="header__link">Туры</a></li>
                  <li><a href="#contacts" className="header__link">Контакты</a></li>
                </ul>
              </nav>
            </div>
          </div>
        </header>

        <section id="welcome" className="welcome">
          <div className="welcome-container">
            <h1 className="welcome-title">Хакасия</h1>
            <p className="welcome-subtitle">Туристическое Агенство Республики Хакасия</p>
          </div>
          <button id="scroll" className="btn_scroll">
            <img src="img/go_down.svg" alt="" />
          </button>
        </section>

        <section id="attractions" className="block">
          <h2 className="block__title">Достопримечательности</h2>
          <div className="block__container">
            <div className="block__item">
              <div className="block__boximg">
                <img className="block__img" src="img/sightseens.png" />
              </div>
              <div className="block__boxtext">
                <h3 className="block__name-item">Тропа предков</h3>
                <p className="block__text-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pretium orci at rutrum pellentesque. Vivamus id nunc at ante vulputate egestas. Sed varius elit ornare condimentum fermentum. Integer mattis pretium tortor dictum tristique. Donec in congue mauris. Quisque vitae nisi ultricies, efficitur odio vel, porta nulla. Donec porta, mauris nec pharetra mollis, diam lorem luctus velit, nec ultricies nunc quam posuere dui. Donec at nisl lorem. Sed vitae sapien metus. In erat felis, pharetra vitae libero eu, posuere accumsan odio. Fusce eget mauris ullamcorper mi fermentum ullamcorper. Donec egestas mollis dolor, a dignissim dolor venenatis eu. Suspendisse quis quam laoreet, mattis neque eu, feugiat lectus. Maecenas non urna mollis, ultricies eros vel, ullamcorper risus. Nulla hendrerit venenatis erat, in rhoncus quam placerat nec. Ut feugiat nisi in mattis lacinia. Morbi eleifend, neque eget dapibus scelerisque, ligula nisl malesuada odio, et imperdiet metus mi pretium enim.</p>
              </div>
            </div>
            <div className="block__item" id="down">
              <div className="block__boximg ">
                <img className="block__img" src="img/sightseens.png" />
              </div>
              <div className="block__boxtext">
                <h3 className="block__name-item">Приисковый</h3>
                <p className="block__text-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pretium orci at rutrum pellentesque. Vivamus id nunc at ante vulputate egestas. Sed varius elit ornare condimentum fermentum. Integer mattis pretium tortor dictum tristique. Donec in congue mauris. Quisque vitae nisi ultricies, efficitur odio vel, porta nulla. Donec porta, mauris nec pharetra mollis, diam lorem luctus velit, nec ultricies nunc quam posuere dui. Donec at nisl lorem. Sed vitae sapien metus. In erat felis, pharetra vitae libero eu, posuere accumsan odio. Fusce eget mauris ullamcorper mi fermentum ullamcorper. Donec egestas mollis dolor, a dignissim dolor venenatis eu. Suspendisse quis quam laoreet, mattis neque eu, feugiat lectus. Maecenas non urna mollis, ultricies eros vel, ullamcorper risus. Nulla hendrerit venenatis erat, in rhoncus quam placerat nec. Ut feugiat nisi in mattis lacinia. Morbi eleifend, neque eget dapibus scelerisque, ligula nisl malesuada odio, et imperdiet metus mi pretium enim.</p>
              </div>
            </div>
            <div className="block__item">
              <div className="block__boximg">
                <img className="block__img" src="img/sightseens.png" />
              </div>
              <div className="block__boxtext">
                <h3 className="block__name-item">Сундуки</h3>
                <p className="block__text-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pretium orci at rutrum pellentesque. Vivamus id nunc at ante vulputate egestas. Sed varius elit ornare condimentum fermentum. Integer mattis pretium tortor dictum tristique. Donec in congue mauris. Quisque vitae nisi ultricies, efficitur odio vel, porta nulla. Donec porta, mauris nec pharetra mollis, diam lorem luctus velit, nec ultricies nunc quam posuere dui. Donec at nisl lorem. Sed vitae sapien metus. In erat felis, pharetra vitae libero eu, posuere accumsan odio. Fusce eget mauris ullamcorper mi fermentum ullamcorper. Donec egestas mollis dolor, a dignissim dolor venenatis eu. Suspendisse quis quam laoreet, mattis neque eu, feugiat lectus. Maecenas non urna mollis, ultricies eros vel, ullamcorper risus. Nulla hendrerit venenatis erat, in rhoncus quam placerat nec. Ut feugiat nisi in mattis lacinia. Morbi eleifend, neque eget dapibus scelerisque, ligula nisl malesuada odio, et imperdiet metus mi pretium enim.</p>
              </div>
            </div>
          </div>
        </section>

        <section id="tours" className="tours">
          <h3 className="tours__title">
            Туры
          </h3>
          <div className="tours__list">
            <div className="tour">
              <div className="container">
                <h4 className="tour__title">Название</h4>
                <p className="tour__short-description">
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci sonsectetur, adipisicing elit. Adipisci s
                </p>
                <span className="tour__price">
                  От <span>10 000</span> р.
                </span>
                <button className="tour__button">
                  Купить
                </button>
              </div>
            </div>

            <div className="tour">
              <div className="container">
                <h4 className="tour__title">Название</h4>
                <p className="tour__short-description">
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci sonsectetur, adipisicing elit. Adipisci s
                </p>
                <span className="tour__price">
                  От <span>10 000</span> р.
                </span>
                <button className="tour__button">
                  Купить
                </button>
              </div>
            </div>

            <div className="tour">
              <div className="container">
                <h4 className="tour__title">Название</h4>
                <p className="tour__short-description">
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci sonsectetur, adipisicing elit. Adipisci s
                </p>
                <span className="tour__price">
                  От <span>10 000</span> р.
                </span>
                <button className="tour__button">
                  Купить
                </button>
              </div>
            </div>

            <div className="tour tour--hidden">
              <div className="container">
                <h4 className="tour__title">Название</h4>
                <p className="tour__short-description">
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci sonsectetur, adipisicing elit. Adipisci s
                </p>
                <span className="tour__price">
                  От <span>10 000</span> р.
                </span>
                <button className="tour__button">
                  Купить
                </button>
              </div>
            </div>

            <div className="tour tour--hidden">
              <div className="container">
                <h4 className="tour__title">Название</h4>
                <p className="tour__short-description">
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci sonsectetur, adipisicing elit. Adipisci s
                </p>
                <span className="tour__price">
                  От <span>10 000</span> р.
                </span>
                <button className="tour__button">
                  Купить
                </button>
              </div>
            </div>

            <div className="tour tour--hidden">
              <div className="container">
                <h4 className="tour__title">Название</h4>
                <p className="tour__short-description">
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci sonsectetur, adipisicing elit. Adipisci s
                </p>
                <span className="tour__price">
                  От <span>10 000</span> р.
                </span>
                <button className="tour__button">
                  Купить
                </button>
              </div>
            </div>
            <button className="btn btn--toggle-items">Больше туров</button>
          </div>
        </section>

        <section id="contacts" className="contacts">
          <h2 className="contacts__title">
            Контакты
          </h2>
          <ul className="contacts__data">
            <li>655019, Республика Хакасия, г. Абакан, пр. Ленина, д. 67</li>
            <li>
              8 (3902) 22-53-35
              <br />
              8 (3902) 24-30-71
            </li>
            <li>kancler@vskhakasia.ru</li>
          </ul>
          <iframe className="contacts__map" src="https://yandex.ru/map-widget/v1/?um=constructor%3A5b2d03754473e3b59ed4fe7c28dfdc7964a8360aeeb7785ae1430a4f091e3aff&amp;source=constructor" width="783" height="400" frameBorder="0"></iframe>
        </section>

        <footer className="footer">
          <ul className="footer__menu">
            <li>Меню</li>
            <li><a href="#welcome" className="header__link">Главная</a></li>
            <li><a href="#attractions" className="header__link">Достопримечательности</a></li>
            <li><a href="#tours" className="header__link">Туры</a></li>
            <li><a href="#contacts" className="header__link">Контакты</a></li>
          </ul>
          <ul className="footer__contacts">
            <li>Контакты</li>
            <li>655019, Республика Хакасия, г. Абакан, пр. Ленина, д. 67</li>
            <li>Справочная служба: 8 (3902) 22-53-35, факс: 8 (3902) 24-30-71</li>
            <li>Электронная почта: kancler@vskhakasia.ru</li>
          </ul>
          <span className="footer__copirate">
            Официальный сайт Агенства Туризма Республики Хакасия  ©  2021
          </span>
        </footer>
      </body>
    </div>
  )
}

export default Home
